###
# @name = Get Belts
GET http://localhost:8080/api/v1/belts

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

# @name = Get Belt
GET http://localhost:8080/api/v1/belts/1

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is text", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/hal+json", "Expected 'application/hal+json' but received '" + type + "'");
    });
%}

###

# @name = Create Belt
POST http://localhost:8080/api/v1/belts
Content-Type: application/json

{
  "name" : "JavaScript",
  "description": "This is a JavaScript belt",
  "category" : "EVENTS"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
    client.global.set("id", response.body.id);
%}

###
# @name = Get Created Belt
GET http://localhost:8080/api/v1/belts/{{id}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###

# @name = Update Belt
PUT http://localhost:8080/api/v1/belts/{{id}}
Content-Type: application/json

{
  "name" : "JavaScriptyytyu",
  "description": "This is a JavaScript belt.",
  "category" : "PROGRAMMING"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# @name = Get Updated Belt
GET http://localhost:8080/api/v1/belts/{{id}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###

# @name = Delete Belt
DELETE http://localhost:8080/api/v1/belts/{{id}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 204, "Response status is not 202");
    });
%}
###

# @name = Confirm Belt Deletion
GET http://localhost:8080/api/v1/belts/{{id}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}
###